CREATE TABLE TRANSACAO	
(
    NU_TRANSACAO_ID INTEGER not null primary key         GENERATED ALWAYS AS IDENTITY         (START WITH 1, INCREMENT BY 1),  
	DT_TRANSACAO	TIMESTAMP,
	VL_TRANSACAO	NUMERIC(12, 2)
);

CREATE TABLE OPERACAO	
(
	NU_OPERCAO_ID INT not null primary key         GENERATED ALWAYS AS IDENTITY         (START WITH 1, INCREMENT BY 1),
	NU_TRANSACAO_ID		INTEGER,
	CD_STATUS_OPERACAO	VARCHAR(2),
	CD_TIPO_OPERACAO	NUMERIC(1, 0) CONSTRAINT CD_TIPO_OPERACAO_CONSTRAINT CHECK (CD_TIPO_OPERACAO IN (1,2,3)),  --1 - "Transferencia"; 2 - Aporte; '3' - Estorno
	DT_OPERACAO			TIMESTAMP,
	VL_OPERACAO			NUMERIC(12, 2),
	CONSTRAINT NU_TRANSACAO_ID_fk FOREIGN KEY (NU_TRANSACAO_ID) REFERENCES TRANSACAO(NU_TRANSACAO_ID)
);

CREATE TABLE PESSOA_JURIDICA	
(
	PESSOA_JURIDICA_ID INTEGER not null primary key         GENERATED ALWAYS AS IDENTITY         (START WITH 1, INCREMENT BY 1),
	RAZAO_SOCIAL		VARCHAR(40),
	NOME_FANTASIA		VARCHAR(40),
	CNPJ				VARCHAR(40)
);

CREATE TABLE PESSOA_FISICA
(
	PESSOA_FISICA_ID 	INTEGER not null primary key         GENERATED ALWAYS AS IDENTITY         (START WITH 1, INCREMENT BY 1),
	RAZAO_SOCIAL		VARCHAR(40),
	NOME_FANTASIA		VARCHAR(40),
	CNPJ				VARCHAR(40)
);

CREATE TABLE CONTA_PESSOA
(
	CONTA_PESSOA_ID 	INTEGER not null primary key         GENERATED ALWAYS AS IDENTITY         (START WITH 1, INCREMENT BY 1),
	PESSOA_FISICA_ID    INTEGER,
	PESSOA_JURIDICA_ID  INTEGER
	
);

CREATE TABLE CONTA	
(
	CONTA_ID INT not null primary key         GENERATED ALWAYS AS IDENTITY         (START WITH 1, INCREMENT BY 1),
	CONTA_PAI_ID 			INTEGER,
	CONTA_PAI_MATRIZ_ID 	INTEGER,
	CONTA_PESSOA_ID			INTEGER,
	TRANSACAO_ID			VARCHAR(40),
	CD_STATUS_OPERACAO		VARCHAR(2),
	CD_TIPO_OPERACAO		NUMERIC(2, 0),
	TP_PESSOA 				CHAR(1) CONSTRAINT TP_PESSOA_CONSTRAINT CHECK (TP_PESSOA IN ('F', 'J')), -- F - FISICA;  J - JURIDICO; 
	DT_CRIACAO				TIMESTAMP,
	VL_OPERACAO				NUMERIC(12, 2),
	SALDO					NUMERIC(12, 2),
	CONSTRAINT CONTA_PAI_ID_fk FOREIGN KEY (CONTA_PAI_ID) REFERENCES CONTA(CONTA_ID),
	CONSTRAINT CONTA_PAI_MATRIZ_ID_fk FOREIGN KEY (CONTA_PAI_MATRIZ_ID) REFERENCES CONTA(CONTA_ID),
	CONSTRAINT CONTA_PESSOA_ID_fk FOREIGN KEY (CONTA_PESSOA_ID) REFERENCES CONTA_PESSOA(CONTA_PESSOA_ID)
);
