CREATE TABLE TRANSACAO	
(
    NU_TRANSACAO_ID INT not null primary key         GENERATED ALWAYS AS IDENTITY         (START WITH 1, INCREMENT BY 1),  
	DT_TRANSACAO	TIMESTAMP,
	VL_TRANSACAO	NUMERIC(12, 2)
);

CREATE TABLE OPERACAO	
(
	NU_OPERCAO_ID INT not null primary key         GENERATED ALWAYS AS IDENTITY         (START WITH 1, INCREMENT BY 1),
	NU_TRANSACAO_ID	INTEGER,
	CD_STATUS_OPERACAO	VARCHAR(2),
	CD_TIPO_OPERACAO	NUMERIC(2, 0),
	DH_OPERACAO		TIMESTAMP,
	VL_OPERACAO		NUMERIC(12, 2)
);

CREATE TABLE CONTA	
(
	NU_CONTA_ID INT not null primary key         GENERATED ALWAYS AS IDENTITY         (START WITH 1, INCREMENT BY 1),
	NU_TRANSACAO_ID	VARCHAR(40),
	CD_STATUS_OPERACAO	VARCHAR(2),
	CD_TIPO_OPERACAO	NUMERIC(2, 0),
	DH_OPERACAO		TIMESTAMP,
	VL_OPERACAO		NUMERIC(12, 2)
);

