INSERT INTO TRANSACAO (DT_TRANSACAO,VL_TRANSACAO) values (CURRENT_TIMESTAMP, 10.0 );


INSERT INTO PESSOA_JURIDICA (RAZAO_SOCIAL,NOME_FANTASIA,CNPJ) VALUES ('HUBFINTECH','VALE PRESENTE','132132100000001-1');
INSERT INTO CONTA_PESSOA (PESSOA_FISICA_ID,PESSOA_JURIDICA_ID) VALUES (NULL,1);


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO, SALDO) VALUES  (NULL,'1',NULL,1,'J',CURRENT_TIMESTAMP, 1000.0);--1
INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO, SALDO) VALUES  (1,'11',1,1,'J',CURRENT_TIMESTAMP, 1000.0);--2
INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO, SALDO) VALUES  (2,'111',1,1,'J',CURRENT_TIMESTAMP, 1000.0);--3
INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO, SALDO) VALUES  (2,'112',1,1,'J',CURRENT_TIMESTAMP, 1000.0);--4
INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO, SALDO) VALUES  (1,'12',1,1,'J',CURRENT_TIMESTAMP, 1000.0);--5
INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO, SALDO) VALUES  (5,'121',1,1,'J',CURRENT_TIMESTAMP, 1000.0);--6


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO, SALDO) VALUES  (NULL,'2',NULL,1,'J',CURRENT_TIMESTAMP, 1000.0);--7
INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO, SALDO) VALUES  (7,'2',NULL,1,'J',CURRENT_TIMESTAMP, 1000.0);--8



	

