INSERT INTO TRANSACAO (DT_TRANSACAO,VL_TRANSACAO) values (CURRENT_TIMESTAMP, 10.0 );


INSERT INTO PESSOA_JURIDICA (RAZAO_SOCIAL,NOME_FANTASIA,CNPJ) VALUES ('HUBFINTECH','VALE PRESENTE','132132100000001-1');
INSERT INTO CONTA_PESSOA (PESSOA_FISICA_ID,PESSOA_JURIDICA_ID) VALUES (NULL,1);


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO) VALUES  (NULL,'1',NULL,1,'J',CURRENT_TIMESTAMP);--1
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (1,1000.0,CURRENT_TIMESTAMP);--1

INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO) VALUES  (1,'11',1,1,'J',CURRENT_TIMESTAMP);--2
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (2,1000.0,CURRENT_TIMESTAMP);--2
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (2,1200.0,CURRENT_TIMESTAMP);--2


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO) VALUES  (2,'111',1,1,'J',CURRENT_TIMESTAMP);--3
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (3,1000.0,CURRENT_TIMESTAMP);--3

INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO) VALUES  (2,'112',1,1,'J',CURRENT_TIMESTAMP);--4
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (4,1000.0,CURRENT_TIMESTAMP);--4


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO) VALUES  (1,'12',1,1,'J',CURRENT_TIMESTAMP);--5
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (5,1000.0,CURRENT_TIMESTAMP);--5

INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO) VALUES  (5,'121',1,1,'J',CURRENT_TIMESTAMP);--6
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (6,1000.0,CURRENT_TIMESTAMP);--6


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO) VALUES  (NULL,'2',NULL,1,'J',CURRENT_TIMESTAMP);--7
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (7,1000.0,CURRENT_TIMESTAMP);--7

INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO) VALUES  (7,'2',NULL,1,'J',CURRENT_TIMESTAMP);--8
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (8,1000.0,CURRENT_TIMESTAMP);--8



	

