INSERT INTO PESSOA_JURIDICA (RAZAO_SOCIAL,NOME_FANTASIA,CNPJ) VALUES ('HUBFINTECH','VALE PRESENTE','132132100000001-1');
INSERT INTO CONTA_PESSOA (PESSOA_FISICA_ID,PESSOA_JURIDICA_ID) VALUES (NULL,1);


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO,STATUS) VALUES  (NULL,'1',NULL,1,'J',CURRENT_TIMESTAMP,'A');--1
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (1,1000.0,CURRENT_TIMESTAMP);--1

INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO,STATUS) VALUES  (1,'11',1,1,'J',CURRENT_TIMESTAMP,'A');--2
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (2,1000.0,  cast({fn timestampadd(SQL_TSI_DAY, -2, current_timestamp)} as timestamp) );--2
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (2,4000.0,  cast({fn timestampadd(SQL_TSI_DAY, -1, current_timestamp)} as timestamp) );--2
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (2,5200.0,CURRENT_TIMESTAMP);--2


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO,STATUS) VALUES  (2,'111',1,1,'J',CURRENT_TIMESTAMP,'A');--3
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (3,1000.0,CURRENT_TIMESTAMP);--3

INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO,STATUS) VALUES  (2,'112',1,1,'J',CURRENT_TIMESTAMP,'A');--4
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (4,1000.0,CURRENT_TIMESTAMP);--4


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO,STATUS) VALUES  (1,'12',1,1,'J',CURRENT_TIMESTAMP,'A');--5
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (5,1000.0,CURRENT_TIMESTAMP);--5

INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO,STATUS) VALUES  (5,'121',1,1,'J',CURRENT_TIMESTAMP,'A');--6
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (6,1000.0,CURRENT_TIMESTAMP);--6


INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO,STATUS) VALUES  (NULL,'2',NULL,1,'J',CURRENT_TIMESTAMP,'A');--7
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (7,1000.0,CURRENT_TIMESTAMP);--7

INSERT INTO CONTA (CONTA_PAI_ID,NOME,CONTA_PAI_MATRIZ_ID,CONTA_PESSOA_ID,TP_PESSOA,DT_CRIACAO,STATUS) VALUES  (7,'2',NULL,1,'J',CURRENT_TIMESTAMP,'A');--8
INSERT INTO SALDO (CONTA_ID,SALDO,DH_ATUALIZACAO) VALUES  (8,1000.0,CURRENT_TIMESTAMP);--8

INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP ,'e25fe2f1e40a74c43a09bf2937611ab4');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP , 'e25fe2f1e40a74c43a09bf2937611a');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a09bf2937611');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a09bf293761');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a09bf29376');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a09bf2937');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a09bf293');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a09bf29');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a09bf');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a09');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a0');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43a');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c43');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c4');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a74c');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40a7');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e40');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e4');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f1e');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2f');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25fe2');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25f');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e25');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e22');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e222');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e2222');
INSERT INTO transacao ( DT_TRANSACAO, CD_APORTE) VALUES (CURRENT_TIMESTAMP, 'e22222');



INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (10, 'A', 0, CURRENT_TIMESTAMP, 500.1);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (10, 'A', 0, CURRENT_TIMESTAMP, 500.1);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (12, 'A', 0, CURRENT_TIMESTAMP, 100);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (14, 'A', 0, CURRENT_TIMESTAMP, 100);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (27, 'A', 1, CURRENT_TIMESTAMP,  50.5);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (26, 'A', 1, CURRENT_TIMESTAMP,  10000);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (24, 'A', 1, CURRENT_TIMESTAMP, 10000);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (23, 'A', 1, CURRENT_TIMESTAMP, 10000);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (22, 'A', 1, CURRENT_TIMESTAMP, 500.1);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (21, 'A', 1, CURRENT_TIMESTAMP, 500.1);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (20, 'A', 1, CURRENT_TIMESTAMP, 500.1);
INSERT INTO operacao (NU_TRANSACAO_ID, CD_STATUS_OPERACAO, CD_TIPO_OPERACAO, DT_OPERACAO, VL_OPERACAO) VALUES (28, 'A', 1, CURRENT_TIMESTAMP,  10000);